@startuml
class ByMomentPdf {
  +{field} Function    : string
  +{field} Moments     : list(Index, double())
  +{field} ParamSolved : list(Index, double())
  +{field} TarFu       : list
  +{field} TarMo       : double()
  +{field} DistaFu     : matrix(double)
  +{field} DistaMo     : matrix(double)
  +{field} DistaMethod : char
  +{field} ParamSpace  : matrix(double)
  +{field} LaunchSpace : matrix(double)
  +{field} Tolerance   : double

  +ByMomentPdf New_ByMomentPdf( TarMo )
  +ByMomentPdf GetLaunchSpace(Pdf, ...)
  +ByMomentPdf SetLaunchSpace(Pdf, ...)
  +ByMomentPdf AddSolution(Pdf, ...)
  +ByMomentPdf FindPdf(Pdf, ...)
  +ByMomentPdf EvaluatePdf(Pdf, ...)
  +numeric()   SolutionMoments(Pdf, ...)
  +numeric()   BestSolution(Pdf, ...)
  .. Access to Pdf ..
  +dPdf(...)
  +pPdf(...)
  +qPdf(...)
  +rPdf(...)
}


class gld {
  +ByMomentPdf New_ByMomentPdf( TarMo )
  +ByMomentPdf FindPdf(Pdf, ...)
  +numeric()   SolutionMoments(Pdf, ...)
  .. hidden ..
  #.FindPDF_GLD(...)
  #.FindPDF_GLD_A3A4(...)
  #.GLDTypeConstraints(...)
  #.DeltaAllGLD(...)
  #.DeltaA3A4GLD(...)
  #.Alpha4( v )
  #.Alpha3( v )
  #.v1f( L3, L4 )
  #.v21f( L3, L4 )
  #.v31f( L3, L4 )
  #.v41f( L3, L4 )
}

class poly {
  +ByMomentPdf New_ByMomentPdf( TarMo )
  +ByMomentPdf FindPdf(Pdf, ...)
  +ByMomentPdf SetLaunchSpace(Pdf, ...)
  .. Access to Pdf ..
  +dPdf(...)
  +qPdf(...)
  +qPdf(...)
  +rPdf(...)
}

class pearson {
  +ByMomentPdf New_ByMomentPdf( TarMo )
  +ByMomentPdf FindPdf(Pdf, ...)
}

  ByMomentPdf <|-- gld
  ByMomentPdf <|-- pearson
  ByMomentPdf <|-- poly
@enduml